/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 4.4.0
 */

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace Cfg
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	[GeneratedCodeAttribute("Hime.SDK", "4.4.0")]
	internal class CfgLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(CfgLexer), "CfgLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "4.4.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x0006;
			/// <summary>
			/// The unique identifier for terminal INTEGER
			/// </summary>
			public const int TerminalInteger = 0x0008;
			/// <summary>
			/// The unique identifier for terminal FLOAT
			/// </summary>
			public const int TerminalFloat = 0x0009;
			/// <summary>
			/// The unique identifier for terminal IDENTIFIER
			/// </summary>
			public const int TerminalIdentifier = 0x000B;
			/// <summary>
			/// The unique identifier for terminal STRING
			/// </summary>
			public const int TerminalString = 0x000C;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "4.4.0")]
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0006, "SEPARATOR"),
			new Symbol(0x0008, "INTEGER"),
			new Symbol(0x0009, "FLOAT"),
			new Symbol(0x000B, "IDENTIFIER"),
			new Symbol(0x000C, "STRING"),
			new Symbol(0x0039, "begin"),
			new Symbol(0x003B, "import"),
			new Symbol(0x003C, ";"),
			new Symbol(0x003D, ":"),
			new Symbol(0x003F, "fork"),
			new Symbol(0x0040, "{"),
			new Symbol(0x0041, "}"),
			new Symbol(0x0042, "for"),
			new Symbol(0x0043, "in"),
			new Symbol(0x0044, "draw"),
			new Symbol(0x0045, "at"),
			new Symbol(0x0046, "return"),
			new Symbol(0x0047, "("),
			new Symbol(0x0048, ")"),
			new Symbol(0x0049, "->"),
			new Symbol(0x004A, "="),
			new Symbol(0x004C, "otherwise"),
			new Symbol(0x004D, "||"),
			new Symbol(0x004E, "&&"),
			new Symbol(0x004F, "=="),
			new Symbol(0x0050, "<"),
			new Symbol(0x0051, ">"),
			new Symbol(0x0052, ">="),
			new Symbol(0x0053, "<="),
			new Symbol(0x0054, "+"),
			new Symbol(0x0055, "-"),
			new Symbol(0x0056, "%"),
			new Symbol(0x0057, "*"),
			new Symbol(0x0058, "/"),
			new Symbol(0x0059, "!"),
			new Symbol(0x005A, ","),
			new Symbol(0x005B, "true"),
			new Symbol(0x005C, "false"),
			new Symbol(0x005D, "."),
			new Symbol(0x005E, ".."),
			new Symbol(0x005F, "..="),
			new Symbol(0x0060, "--"),
			new Symbol(0x0061, "~~"),
			new Symbol(0x0064, "(|"),
			new Symbol(0x0065, "|)"),
			new Symbol(0x0067, "["),
			new Symbol(0x0068, "]"),
			new Symbol(0x006B, "left"),
			new Symbol(0x006C, "right"),
			new Symbol(0x006D, "top"),
			new Symbol(0x006E, "bottom"),
			new Symbol(0x006F, "on"),
			new Symbol(0x0070, "place"),
			new Symbol(0x0071, "scale"),
			new Symbol(0x0072, "by"),
			new Symbol(0x0073, "rotate"),
			new Symbol(0x0075, "int"),
			new Symbol(0x0076, "float"),
			new Symbol(0x0077, "point"),
			new Symbol(0x0078, "color"),
			new Symbol(0x0079, "shape"),
			new Symbol(0x007A, "path"),
			new Symbol(0x007B, "polygon"),
			new Symbol(0x007C, "bool"),
			new Symbol(0x007D, "[]") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public CfgLexer(string input) : base(commonAutomaton, terminals, 0x0006, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public CfgLexer(TextReader input) : base(commonAutomaton, terminals, 0x0006, input) {}
	}
}
